import { z } from "zod";

/** An opaque, hex-encoded token as generated by
 * `utils/token.util.ts`'s `generateRawToken` — validated only for
 * shape here; whether it's actually valid (exists, unexpired, unused)
 * is a service-layer, database-backed check. */
export const rawTokenSchema = z.string().min(1, "Token is required");
