export {
  BRAND_DESCRIPTION_MAX_LENGTH,
  BRAND_FILTERABLE_FIELDS,
  BRAND_NAME_MAX_LENGTH,
  BRAND_NAME_MIN_LENGTH,
  BRAND_SLUG_MAX_LENGTH,
  BRAND_SLUG_PATTERN,
  BRAND_SORTABLE_FIELDS,
  BRAND_STATUSES,
  BRAND_URL_MAX_LENGTH,
} from "./brand.constants";
export type { BrandStatus } from "./brand.constants";
