export type JwtTokenType = "access" | "refresh";

/**
 * Claims supplied by the caller when signing an access token. `roles` is
 * always an array — empty when the subject has none — never optional, so
 * downstream code never has to guard against it being missing. No
 * concrete role values exist yet; this is the mechanism, not a role
 * system.
 */
export interface AccessTokenClaims {
  sub: string;
  roles: string[];
}

export interface RefreshTokenClaims {
  sub: string;
}

export interface AccessTokenPayload extends AccessTokenClaims {
  type: "access";
  iat: number;
  exp: number;
}

export interface RefreshTokenPayload extends RefreshTokenClaims {
  type: "refresh";
  /** A random id unique to this specific signed token, generated by
   * `signRefreshToken` — never supplied by the caller. Guarantees two
   * refresh tokens for the same subject are never byte-identical even
   * if issued within the same second (JWT signing is otherwise
   * deterministic: identical claims + identical `iat` produce identical
   * output), which matters wherever a token's hash is stored as a
   * unique key — see `modules/auth`'s `RefreshToken` persistence. */
  jti: string;
  iat: number;
  exp: number;
}

export interface TokenPair {
  accessToken: string;
  refreshToken: string;
}
